arb-dir: lib/gen/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
nullable-getter: false
# untranslated-messages-file: desiredFileName.txt
# Trigger assert when key is missing in translation
untranslated-mandatory: true
# Allow duplicate key? -> false to make CI fail early
# (only available from Flutter 3.19)
no-duplicate-keys: false