# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'json'
# require 'dotenv'

# Dotenv.load '.env'

# def load_firebase_config(env)
#   config_file = File.read(File.join(__dir__, 'firebase_config.json'))
#   config = JSON.parse(config_file)
#   config[env]
# end

default_platform(:android)

platform :android do
  lane :app_distribution do |options|
    env = options[:env] || "prod"
    
    config = JSON.parse(File.read('firebase_config.json'))[env]
    fastlane_root = File.expand_path(".",__dir__)

    app_id = config['app_id']
    groups_file = File.join(fastlane_root,config['groups_file'])
    service_credentials_file = File.join(fastlane_root,config['service_credentials_file'])
    release_notes_file = File.join(fastlane_root,config['release_notes_file'])

    puts "env: #{env}"
    puts "app_id: #{app_id}"
    puts "groups_file: #{groups_file}"
    puts "service_credentials_file: #{service_credentials_file}"
    puts "release_notes_file: #{release_notes_file}"
    
    sh("fvm", "flutter", "clean")
    # sh("fvm", "flutter", "packages", "get")
    # sh("fvm", "flutter", "pub", "run", "build_runner", "build", "--delete-conflicting-outputs")
    sh("fvm", "flutter", "build", "apk", "--flavor", "#{env}", "-t", "lib/main_#{env}.dart")
  
    # Define the root directory of the project
    root_dir = File.expand_path("../../", __dir__)

    # Construct the APK path dynamically from the root directory
    apk_path = "#{root_dir}/build/app/outputs/apk/#{env}/release/app-#{env}-release.apk"

    puts "Using APK path: #{apk_path}"
    
    firebase_app_distribution(
      app: app_id,
      apk_path: apk_path,
      groups_file: groups_file,
      service_credentials_file: service_credentials_file,
      release_notes_file: release_notes_file
    )
  end

  lane :app_distribution_dev do
    app_distribution(env: "dev")
  end

  lane :app_distribution_prod do
    app_distribution(env: "prod")
  end

  lane :play_store do |options|
    track = options[:track]
    puts "track in options: #{track}"
    if !options[:track]
      track = "internal"
    end
    puts "track: #{track}"

    env = options[:env]
    if !env
      env = "prod"
    end
    fastlane_root = File.expand_path(".",__dir__)

    sh("fvm","flutter","clean")
    # sh("fvm","flutter","packages", "get")
    # sh("fvm","flutter","pub","run","build_runner","build","--delete-conflicting-outputs")
    sh("fvm","flutter", "build", "appbundle", "--flavor", env, "--release", "-t", "lib/main_#{env}.dart")

    aab_path = "../build/app/outputs/bundle/#{env}Release/app-#{env}-release.aab"
    upload_to_play_store(
      track: track,
      aab: aab_path,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_apk: true
    )
  end
  
end
